[package]
name = "cmd"
version = "0.0.1"
description = "basjoofan command"
repository = "https://github.com/basjoofan/lib"
license = "MIT OR Apache-2.0"
authors = ["Lamb <lamb@basjoofan.com>"]
keywords = ["continuous", "test", "http"]
edition = "2021"

[[bin]]
name = "basjoofan"
path = "src/main.rs"

[dependencies]
lib = { path = "../lib" }
clap = { version = "4.5.28", features = ["derive"] }
ctrlc = { version = "3.4.5"}

[dev-dependencies]
assert_cmd = "2.0.16"
assert_fs = "1.1.2"
predicates = "3.1.3"
